angular.module('app')
  .controller('homeController',['$scope','API',function($scope,API){
  	    $scope.getaa=function(){
  	    	console.log(1);
          API.aa('http://127.0.0.1:9000/message')
          .then(function(data){
                  console.log(data);
          })
        }
  }])